### ISSUE TITLE
hi, I want to know how to use this to calculate 3' RNAseq data?

### ISSUE THREAD

**Issue by DawnEve** [morrislab/qapa#1]
we have some scRNA-seq data from C1 system. Mapping plot shows it's a kind of 3' end RNA seq.

how to process these data, i couldn't quit know these info even after reading your paper and readme on github.

I'm a newbie about APA, would u mind to show me more clearly?
Thank you.  

George.

**Comment by quaidmorris** [comment]
Hi,
Thanks for your interest in QAPA. I'm sorry, we are unable to provide this
type of assistance. You may be able to find the help that you need on
https://www.biostars.org/.

Best,
Quaid.

Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.ca <http://morrislab.med.utoronto.ca>
cell:  (416) 220 5796

**Comment by DawnEve** [comment]
This means QAPA cannot solve 3' end RNAseq data from C1 system?

 I'll try other packages then.

Thank you.

**Comment by quaidmorris** [comment]
Did you read the paper? The focus of QAPA is on normal RNA-seq data, not 3'
end seq.

Quaid Morris, PhD
Associate Professor, The Donnelly Centre
Departments of Molecular Genetics and Computer Science
160 College St,  Rm 616
Toronto ON, M5S 3E1 Canada
http://morrislab.ca <http://morrislab.med.utoronto.ca>
cell:  (416) 220 5796

**Comment by kcha** [comment]
Hi George,

Unfortunately QAPA doesn't support scRNA-seq platforms at this time. 

Kevin

**Comment by DawnEve** [comment]
@quaidmorris I have read thourouly as I have mentioned. 
At the topleft of page 13 on your paper, there is a quarter page talking about processing 3' end data, but I think it's vague as I'm new in this area. I thought it was part of QAPA's function.

@kcha Hi, I think it is not a matter of sc or not. If the tool is effitient enough on bulk seq data, it may be used in sc seq data. Just my opinion.
