### ISSUE TITLE
Is QAPA suitable for tot-RNA-Seq?

### ISSUE THREAD

**Issue by xflicsu** [morrislab/qapa#12]
As the title question described, what type of RNA-Seq can handle by QAPA?
mRNA-Seq (capture mRNA with poly A tail)
tot-RNA-Seq (rRNA removed)

**Comment by quaidmorris** [comment]
Hi Xianfeng,
Thanks for your question!

I see no reason why QAPA can't handle tot-RNA-Seq.

**Comment by kcha** [comment]
Hi Xianfeng,

QAPA should be suitable for total RNA-seq. In our work we have been using poly(A)-selected RNA-seq.

**Comment by xflicsu** [comment]
> Hi Xianfeng,
> 
> QAPA should be suitable for total RNA-seq. In our work we have been using poly(A)-selected RNA-seq.

Thanks all for your response!
