### ISSUE TITLE
Build Library for Drosophila

### ISSUE THREAD

**Issue by leggles** [morrislab/qapa#14]
I am trying to use QAPA for RNA-Seq data from D.melanogaster, and as such I am building the library from scratch.  This is the error message I am receiving:
<img width="1339" alt="Screen Shot 2019-04-17 at 9 57 59 AM" src="https://user-images.githubusercontent.com/46731872/56306435-4e65e500-60f7-11e9-9fd9-9d0d55a17d73.png">

I have tried downloading the Ensembl gene metadata table from Biomart in different formats (both TSV and CSV).  The bed file is custom made bed12 format using bedrolls from 3' seq data on a sample of D.melanogaster heads.  The dm6.txt file is gene annotations from UCSC.  I can also easily email any files to be looked at in order to better figure out where the issue might be.  Thank you for your time and considering in addressing my concern.

**Comment by kcha** [comment]
Hi @leggles, 

This might be a type issue due to Python 2 vs Python 3. I had previously fixed a related bug in the master branch. Can you pull the latest changes form master and try again? Alternatively, I just posted a new release containing the latest changes: https://github.com/morrislab/qapa/releases/tag/v1.2.2. Moving forward, I will most likely be dropping support for Python 2 in favour of Python 3.

**Comment by leggles** [comment]
Attachments available until May 23, 2019
Kevin,
     I am still unable to get the build subcommand to run without error.  Can you take a look at my input files and let me know if you are able to detect a problem?  I greatly appreciate your time.

Lauryn
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAcQo8a4b8FkVicF2Ll-H5PkYLKh8Ad8EFUxMTSZwN0uaS4GS9NshLu0X%2F%24%7Bf%7D%3Fo%3DAlcQyIc-0aLnN3x1UBCZ_DM3MaL0gwE7ZkYzYDVi_LAR%26v%3D1%26x%3D3%26a%3DCAoga1qUyjUakrr7l01Xg9no6mLp6no6xM2k6bLR50k3Ko0SGxDu-LbdpC0Y7oiysa4tIgEAKggByAD_bfKyBQ%26e%3D1558639838%26k%3D%24%7Buk%7D%26fl%3D%26r%3DBC908A74-561F-4158-9FBF-CBA8ED80A126-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D9977A87B-37B9-472C-8C2D-AA97B4814A41%26p%3D52%26s%3DA9uUDoUnDQ5PfN43pXR59ZeY4wI&uk=1w7M7JYabrD8d_z5IXztkw&f=3seq_dme_head.bed.gz&sz=177342625>3seq_dme_head.bed.gz
177.3 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAflFQYOH8s3WsVWp0u7bHKAJfhnKAaOU7tI4ysGve_9SlRUDZ8e5ki0j%2F%24%7Bf%7D%3Fo%3DArGrT-SV76PGdbKKtH1j8QA5rpsKaVmFzMNIFJ5OeOlK%26v%3D1%26x%3D3%26a%3DCAogZTAp5k0_-N71JwwZyiYLVHUAzjDSjHixZYqL_dOnUJQSGxCt-bbdpC0YrYmysa4tIgEAKggByAD_be6Z1w%26e%3D1558639838%26k%3D%24%7Buk%7D%26fl%3D%26r%3D3559A0B9-A6E7-415F-859D-769B7A2F3A38-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D9977A87B-37B9-472C-8C2D-AA97B4814A41%26p%3D52%26s%3DkDGbw4ChD6XrXIZ-4TEto9_Ev6M&uk=QE2h3WBpAlGdUdAWSUev3A&f=ensembl_identifiers.txt.gz&sz=336762>ensembl_identifiers.txt.gz
337 KB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FARk5ER6Dw21CBN47LtlHpekiizUeAfXnRGDjVnhDhb8ogeo4qbrLi7bE%2F%24%7Bf%7D%3Fo%3DAi7GXCVu5H6MhjOstbT140qzMCR9kc4KsCixn12QZbVm%26v%3D1%26x%3D3%26a%3DCAogLvdaM4Q0mJulgefZ8midBajsdrmC0Rp2PD3ffOr0R4oSGxCH-7bdpC0Yh4uysa4tIgEAKggByAD_ahd-Lg%26e%3D1558639838%26k%3D%24%7Buk%7D%26fl%3D%26r%3D80489982-CC81-4861-8D97-C2D89234E68E-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D9977A87B-37B9-472C-8C2D-AA97B4814A41%26p%3D52%26s%3DOhg8HyMtvuRQiQqKYTMoKzJKJ9k&uk=hDFl3B0diXFvY5p0xWu-Uw&f=dm6.genedPred.gz&sz=1089279>dm6.genedPred.gz
1.1 MB

**Comment by kcha** [comment]
Hi @leggles,

Thanks for providing your input data for me to diagnose. I have two suggestions:

1. What command did you use to build your dm6.genedPred.gz file? If you used the `gtfToGenePred` tool, then you need to include the `-genePredExt` option to produce the extended format. 

2. In order for the annotation step to work, the chromosome naming convention in 3seq_dme_head.bed.gz must match with those in dm6.genedPred.gz. Currently they do not match -- one file does not have the "chr" prefix, while the other does:

```
>gzip -dc 3seq_dme_head.bed.gz | cut -f 1 | sort | uniq | head
2L
2LHet
2R
2RHet
3L
3LHet
3R
3RHet
4
U
>gzip -dc dm6.genedPred.gz | cut -f 2 | sort | uniq | head
chr2L
chr2R
chr3L
chr3R
chr4
chrUn_CP007081v1
chrUn_CP007102v1
chrUn_CP007120v1
chrUn_DS483646v1
chrUn_DS483910v1
```

**Comment by leggles** [comment]
Kevin,
     Previously I was using a script from polyAsite to generate my custom BED file from 3' sequencing data, but instead I tried making a custom BED file by hand, starting with only 5 genes of interest as a test.  First I received this error message:

<img width="1356" alt="Screen Shot 2019-06-12 at 9 54 34 AM" src="https://user-images.githubusercontent.com/46731872/59372443-5f4c6480-8cfc-11e9-8cf1-06f5ca5aaab6.png">
 
     I thought the problem might be that the gene metadata table from BioMart (ensembl_identifiers.txt) is built from the dm6 genome annotation, and my custom BED file (dm3.bed) is dm3, so I used the UCSC liftOver tool to convert the BED file and tried again.  Note that I changed the name of ensembl_identifiers.txt to ensembl_identifiers.dm6.txt to represent this, although the file is the same in the first and second attempts.  Also, this second attempt was using a gtfToGenePred converted gene annotation from the UCSC Table Browser (dm6.genedPred), and I made sure the -genePredExt option was used.  This is the error message received:

<img width="1370" alt="Screen Shot 2019-06-12 at 10 13 42 AM" src="https://user-images.githubusercontent.com/46731872/59372745-00d3b600-8cfd-11e9-9698-49aa38a35c36.png">

I will attach all the files used in these attempts in case it might help determine the source of this error.  I greatly appreciate your help in this, as I have been struggling with it for a while.


[dm3_gene_annotation.dms.gz](https://github.com/morrislab/qapa/files/3282522/dm3_gene_annotation.dms.gz)

[dm6.genedPred.gz](https://github.com/morrislab/qapa/files/3282523/dm6.genedPred.gz)

[ensembl_identifiers.dm6.txt.gz](https://github.com/morrislab/qapa/files/3282524/ensembl_identifiers.dm6.txt.gz)

[dm3.bed.gz](https://github.com/morrislab/qapa/files/3282526/dm3.bed.gz)

[dm6.bed.gz](https://github.com/morrislab/qapa/files/3282527/dm6.bed.gz)

**Comment by kcha** [comment]
Hi @leggles, thanks for sharing your files. I think the issue is that the identifiers in your genePred file are in RefSeq format. As a result, they can't be matched with records in `ensembl_identifiers.dm6.txt`. The gene identifiers in the genePred file should be in Ensembl format.
