### ISSUE TITLE
Build library for rat

### ISSUE THREAD

**Issue by jchariker** [morrislab/qapa#21]
Hi,
I am following instructions to build a library for rat, and I am getting an error using the following command: 
qapa build -N --db Rn6_Ensembl_sorted.txt Rn6_Gencode.txt > output.utrs.bed

The error message is:
[qapa] Error: 
Command was:
	bedtools groupby -o collapse,collapse,collapse,collapse -i /tmp/pybedtools.rq16ugfd.tmp -g 1,2,3,6,7,8,9 -delim | -c 4,5,10,11
Error message was:
*****
***** ERROR: Requested column 4, but database file /tmp/pybedtools.rq16ugfd.tmp only has fields 1 - 0.

I attached the Ensembl and Gencode files. They appear similar to the example files you posted for human and mouse. Do you have any thoughts on what might be going wrong?
Thanks for any help you can give me.
Julia
[Rn6_Ensembl_sorted.txt](https://github.com/morrislab/qapa/files/3444174/Rn6_Ensembl_sorted.txt)
[Rn6_Gencode.txt](https://github.com/morrislab/qapa/files/3444175/Rn6_Gencode.txt)

**Comment by kcha** [comment]
Hi Julia, thanks for your question and posting your files. Indeed there was a bug in handling Ensembl IDs for species other than human and mouse. I have pushed a fix which should resolve your issue now. Hope this helps! If not, feel free to reopen this issue.

**Comment by jchariker** [comment]
Thank you very much. It works beautifully now!
Julia
