### ISSUE TITLE
No alignment to eIF3b

### ISSUE THREAD

**Issue by latacca** [morrislab/qapa#23]
Hello, 

I have tried two different datasets using the UTR_library and ensembl.identifiers.txt.gz provided in the GitHub and when I look at the output .txt nothing maps to eIF3B. This is an essential gene and therefore it is very likely that this issue is not biological. Any ideas of what's happening?

**Comment by kcha** [comment]
Hi @latacca 

I took a look at eIF3B and I think the reason is that eIF3B contains an intron in the 3' UTR, which was filtered out by the analysis.

**Comment by latacca** [comment]
Thank you, I will look at that one manually.
