### ISSUE TITLE
visualize pau_text output file in IGV

### ISSUE THREAD

**Issue by YONGJINGYEN** [morrislab/qapa#24]
Hi, 

May I know how can I visualize pau_output.txt in IGV?

**Comment by kcha** [comment]
Hi, there is no way to visualize this output on IGV. Instead, you can supply BAM files to IGV to do visualization.

**Comment by YONGJINGYEN** [comment]
Dear Kevin,

It is good to hear from you. Using salmon quant, I mapped .fastq reads to an indexed 3'UTR library for transcript-level quantification. However, salmon program doesn't provide alignment intermediate files.

So are you suggesting to me that I can use BAM files from Tophat program to infer expression level of alternative 3' UTR isoform resulted from QAPA? As we would like to visually 'validate' QAPA results before proceeding to experimental validation, hope you can help us with that:)

Thank you for the discussion!!😊

Best regards,
Jing Yen
________________________________

**Comment by kcha** [comment]
Yes for visualization purposes, you will need to generate a BAM file using an aligner like TopHat or HISAT2.
