### ISSUE TITLE
error: Insufficient number of columns in gene prediction file

### ISSUE THREAD

**Issue by shannjiang** [morrislab/qapa#25]
Hi to Morris lab member,

I am running qapa with the following command:
qapa build -H --db gencode_v31_ensembl_identifier_v2.txt -o GEOCODE_v31_polyA.bed gencode.v31.primary_assembly.annotation.genePred > output_utrs.bed

Returned the following error:
[qapa] Version 1.2.3
[qapa] Extracting 3' UTRs from table
/opt/anaconda3/lib/python3.5/site-packages/qapa-1.2.3-py3.5.egg/qapa/extract.py:131: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  conn = pd.read_table(args.db)
[qapa] Error: Insufficient number of columns in gene prediction file.
[qapa] Finished!

What's the gene prediction file? How to resolve the issue?

thanks,

Shan

**Comment by kcha** [comment]
The gene prediction file is your `gencode.v31.primary_assembly.annotation.genePred`. The error means that this file is missing some columns. How did you produce this file? Did you use `gtfToGenePred -genePredExt`?

**Comment by shannjiang** [comment]
Hi @kcha , I used gtfToGenePred but didn't use the genePredExt flag. I used the basic annotation file from UCSC instead of .genePred finally. It works. I would close the issue.
