### ISSUE TITLE
salmon/salfish index procedure

### ISSUE THREAD

**Issue by cjhong** [morrislab/qapa#3]
Hi, Salmon or Salfish procedure is not clear. Need more details. For example,
-Which Salmon transcript FASTA file I need to build index with?

**Comment by kcha** [comment]
After creating your 3' UTR FASTA library (or using the pre-built ones), you can use Salmon to index that file. e.g:
```
salmon index -t qapa_3utrs.gencode.mm10.fa -i mm10_utr
```
