### ISSUE TITLE
The mapping rate is low when using salmon to quant the transcript expression with utr_library.

### ISSUE THREAD

**Issue by langke307** [morrislab/qapa#31]
Hi kcha,
I  generated the 3'UTR index named utr_library/ to qaunt the transcript expression with salmon  following the github usage. However, the mapping rate in each of the sample log is 25%-35%. 
The commond I used is:
**salmon quant -i utr_library/ -l A  -r ../time_SRR/sample.fastq -o data/sample**

I guessed the low mapping rate may caused because of many reads are not mapped to the genome region except 3'UTR，but I'm not sure of that. Is this a normal phenomenon?

**Comment by kcha** [comment]
Yes, because the reads are only mapping to the 3' UTR, you would expect a low mapping rate.
