### ISSUE TITLE
Error of salmon indexing

### ISSUE THREAD

**Issue by chilampoon** [morrislab/qapa#33]
Hi,

When I ran `salmon index -t output_sequences.fa -i utr_library`, an error occurred:

`ERROR!! DOESN'T SUPPORT STRING LENGTH LONGER THAN 255. String length: 317`.
I am using human hg38 data, the output_sequences.fa is from:

`qapa fasta -f utr/genome/hg38/hg38.fa qapa/qapa_3utrs.gencode_V31.hg38.bed res.qapa/output_sequences.fa`

Is there any way to solve it?

**Comment by chilampoon** [comment]
I've reported this issue to people maintaining Salmon, they said Salmon v0.15 should be OK and will fix this problem for the lasted version.

**Comment by kcha** [comment]
Sorry for the delay. Unfortunately, I don't have an answer to this issue, but glad you were able to find a resolution.
