### ISSUE TITLE
Raw read counts from salmon_quant files

### ISSUE THREAD

**Issue by snosna** [morrislab/qapa#36]
Is there an option during `qapa quant` to also output the raw read counts from the salmon/sailfish quantification files? This would be for compatibility of the `qapa` results with other differential gene expression analysis methods (namely, `DESeq2` in my case).

**Comment by kcha** [comment]
Sorry, this is not possible. You'll have to go back to your quant files to get them.

**Comment by snosna** [comment]
Thanks for the response! I should have checked the functionality of `create_merged_data.R` more carefully before posting this question. By setting the `-f` flag to `NumReads`, it is possible to obtain just the raw reads from the salmon/sailfish quantification files (which is what I want). I checked the source code for this R script briefly and when reading in the salmon/sailfish quantification data, `NumReads` is loaded as well, so I think this is why it works.

**Comment by kcha** [comment]
That's a good find. It's not an advertised option, but glad it works for you.
