### ISSUE TITLE
QAPA fasta ERRO

### ISSUE THREAD

**Issue by wqy399** [morrislab/qapa#40]
Hi, when I use QAPA to extract sequences from mm10.fa with the following command: qapa fasta -f mm10_ucsc.fa output_utrs.bed output_sequences.fa, I got this error:TypeError: expected str, bytes or os.PathLike object, not FileInput. 
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/64593283/95834525-aa9ed900-0d6f-11eb-85d0-05908cd30c24.png">
Could you please help me to figure out what's wrong with it.
Here is part of the bed file.
<img width="974" alt="image" src="https://user-images.githubusercontent.com/64593283/95834809-010c1780-0d70-11eb-89bd-fdcccfe40592.png">
Would you please help me to figure out what's wrong with that ?

**Comment by wqy399** [comment]
Python version is 3.7, bedtools version is 2.25.0

**Comment by quaidmorris** [comment]
Is mm10_ucsc.fa uncompressed and in the directory that you are calling qapa from?

**Comment by wqy399** [comment]
Thanks for your reply. 
Yes. I am sure the fasta file located correctly in the same directory. And I guess this ERRO has something with the python versions or configs or something like that. This problem really confuses me for days and my lab-mates can not figure out as well. 
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/64593283/95938215-fc953c80-0e0b-11eb-92c3-1ce177b756f4.png">
Thats all the files in the directory. I got the output_sequences.fa but it is empty.
A lot thanks for your help!

**Comment by kcha** [comment]
Can you try downgrading Biopython (maybe 1.76?). The error seems to be something related to that package. Maybe there was a breaking change, but I'm not sure.

**Comment by wqy399** [comment]
Wow! It worked well after I degraded the Biopython to version 1.76. 
Thanks a lot!!!!!!

**Comment by kcha** [comment]
Thanks for catching this. I will make some changes to address this issue when I get the chance.
