### ISSUE TITLE
hg38 3'UTR data and ensembl identifiers

### ISSUE THREAD

**Issue by jalalsiddiqui** [morrislab/qapa#41]
I would like to know if using the pre-annotated 3'utr data for hg38 will work with the ensembl identifiers (which state hg19). I have done some preliminary work and they seem to be the same.

**Comment by kcha** [comment]
Hi @jalalsiddiqui, good question. It should be ok, but it might not hurt to re-download a new set of Ensembl identifiers (step A here: https://github.com/morrislab/qapa#prepare-annotation-files).
