### ISSUE TITLE
A problem about qapa build

### ISSUE THREAD

**Issue by NJU-Bio-Info** [morrislab/qapa#43]
Distinguish tool!!!!

When I use qapa build, I have use
`gtfToGenePred -genePredExt gencode.v38.annotation.gtf gencode.v38.annotation.genePred` to produce genePred file

The format of this file is:
ENST00000456328.2       chr1    +       11868   14409   14409   14409   3       11868,12612,13220,      12227,12721,14409,      0       ENSG00000223972.5
ENST00000450305.2       chr1    +       12009   13670   13670   13670   6       12009,12178,12612,12974,13220,13452,    12057,12227,12697,13052,13374,136
ENST00000488147.1       chr1    -       14403   29570   29570   29570   11      14403,15004,15795,16606,16857,17232,17605,17914,18267,24737,29533,      1

and the polyA bed file I used is:
chr1    141473  141475  383461  0       -
chr1    266353  266355  383465  0       -
chr1    365508  365510  383468  0       +
chr1    366048  366050  383470  0       +
chr1    594452  594454  383471  0       -
chr1    594572  594574  383474  0       +

and the identifier file is :
Gene stable ID  Transcript stable ID    Gene type       Transcript type Gene name
ENSG00000223972.5       ENST00000456328.2       transcribed_unprocessed_pseudogene      processed_transcript    DDX11L1
ENSG00000223972.5       ENST00000450305.2       transcribed_unprocessed_pseudogene      transcribed_unprocessed_pseudogene      DDX11L1
ENSG00000227232.5       ENST00000488147.1       unprocessed_pseudogene  unprocessed_pseudogene  WASH7P
ENSG00000278267.1       ENST00000619216.1       miRNA   miRNA   MIR6859-1

but when I run qapa build:
`qapa build --db ensembl.identifier.txt -o gencode.v38.polyA.bed gencode.v38.annotation.genePred > output_utrs.bed`
it gave me the following message:
qapa.qapa     - 2022-03-14 14:20:34,329 - INFO     - Version 1.3.2
qapa.qapa     - 2022-03-14 14:20:35,199 - INFO     - Extracting 3' UTRs from gencode.v38.annotation.genePred
qapa.extract  - 2022-03-14 14:20:41,121 - WARNING  - 237012/237012 (1.00%) were skipped. Are you using the correct database?
qapa.qapa     - 2022-03-14 14:20:41,131 - INFO     - Annotating 3' UTRs
qapa.annotate - 2022-03-14 14:20:41,132 - INFO     - Annotating with gencode.v38.polyA.bed
qapa.qapa     - 2022-03-14 14:20:41,841 - ERROR    - Error occurred in build:
Traceback (most recent call last):
  File "/share/apps/anaconda3/envs/qapa/lib/python3.9/site-packages/qapa-1.3.2-py3.9.egg/qapa/qapa.py", line 231, in build
    annotate.main(args, tf1.name, tf2)
  File "/share/apps/anaconda3/envs/qapa/lib/python3.9/site-packages/qapa-1.3.2-py3.9.egg/qapa/annotate.py", line 238, in main
    overlap_utrs = sort_bed(overlap_utrs)\
  File "/share/apps/anaconda3/envs/qapa/lib/python3.9/site-packages/pybedtools/bedtool.py", line 923, in decorated
    result = method(self, *args, **kwargs)
  File "/share/apps/anaconda3/envs/qapa/lib/python3.9/site-packages/pybedtools/bedtool.py", line 402, in wrapped
    stream = call_bedtools(
  File "/share/apps/anaconda3/envs/qapa/lib/python3.9/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools groupby -o collapse,collapse,collapse,collapse -i /tmp/pybedtools.xe_k4uz9.tmp -g 1,2,3,6,7,8,9 -delim | -c 4,5,10,11

Error message was:

*****
***** ERROR: Requested column 4, but database file /tmp/pybedtools.xe_k4uz9.tmp only has fields 1 - 0.

So how can I solve such problem and I have checked the previous issue and checked the format of my input file, but it seems make no sense. Thank you ~

**Comment by NJU-Bio-Info** [comment]
@kcha

**Comment by kcha** [comment]
I think the issue may be further upstream with the warning that 237012/237012 of your entries were skipped -- meaning no 3' UTRs could be extracted from your genePred file. There are a few possibilities why this could be happening. 

 - your identifier file does not contain any protein coding genes.
 - your identifier file is the wrong organism and could not be matched with the identifiers in the genePred file.
 
I tried downloading a gencode v38 GTF file, converted to genePred and run `qapa build`, but could not reproduce the same warning.

**Comment by xiaoying201355** [comment]
Hey, I have met similar problems, later I have found that the extract.py has a function get_stripped_name, so accordingly the transcript stable ID in the identifier file needs to be stripped of the dot and the version, then it could work. This should be included in the doc since it's prone to neglect this ID conversion.

**Comment by kcha** [comment]
Thanks for the explanation. I think I understand the issue a bit better now.

Looking back at the example above, I'm not sure how you could have obtained the identifiers file such that the `Gene stable ID` and `Transcript stable ID` columns contain versioned identifiers. The correct format should have been non-versioned identifiers. So you are right that stripping the version number would solve the issue, but shouldn't have been necessary to begin with.

The correct column headings for versioned identifiers should be `Gene stable ID version` and `Transcript stable ID version`, neither of which are required for the identifiers file.

**Comment by NJU-Bio-Info** [comment]
Yeah, when I removed the version information of transcripts IDs, it can work well. Send my great thanks to you again!!! @kcha @xiaoying201355
