### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'debug'

### ISSUE THREAD

**Issue by AdiTecki** [morrislab/qapa#44]
Hi,

I'm trying to run qapa quant but I have this error message each time :

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/qapa/bin/qapa", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/qapa/lib/python3.9/site-packages/qapa/qapa.py", line 288, in main
    if args.debug:
AttributeError: 'Namespace' object has no attribute 'debug'
```

The input commande is  : 

`qapa quant --db ensembl_identifiers.txt quant_files abundance_files/* > pau_results.txt`

Inside abundance_files I have my bam files. I respected all the step before qapa quant.

Thanks you

**Comment by kcha** [comment]
Thanks for catching this. Looks like a bug introduced from the recent updates.

**Comment by kcha** [comment]
@AdiTecki should be fixed now. Try pulling the repo and installing again.

BTW, QAPA won't work with bam files, only the quant files.

**Comment by AdiTecki** [comment]
Ok thank you I will test that ! 

I used ".abundance" files from StringTie, is it good ?
