### ISSUE TITLE
Error in qapa quant

### ISSUE THREAD

**Issue by Prakrithi-P** [morrislab/qapa#47]
Hi team,
     I get the following error (image attached) while running qapa quant. Could you please help me identify where I am going wrong?
<img width="1352" alt="qapa_quant_error" src="https://user-images.githubusercontent.com/70966155/203341694-9c1d82e2-39b9-4eb3-85b7-ce38a840f68f.png">

Command: qapa quant --db ../../human_ref/hg38_biomart_qapa_db.txt ST_test/HN*/quant.sf > ST_test/qapa_results

The db file is as in the image attached
<img width="932" alt="image" src="https://user-images.githubusercontent.com/70966155/203341572-e86f625a-9dca-4742-ab07-37835beead1f.png">

Thanks & regards,
Prakrithi

**Comment by jakiwaibl** [comment]
Hi qapa team,
I just recently received the same error while running qapa quant. I used a customized BED file and checked the matching Ensembl ID versions of the database file and quant.sf, there are 100% matches when checking manully (both genes and transcripts).

Here are the commands:

**Gene annotation:** 
![image](https://user-images.githubusercontent.com/93919928/206456033-efa58a8b-79fa-41fd-b968-e4cfd0d03919.png)
![image](https://user-images.githubusercontent.com/93919928/206456148-1074fab0-393d-4811-9773-b39d131b2aff.png)
![image](https://user-images.githubusercontent.com/93919928/206456181-78f19376-975d-436b-a020-ebc3b8143ac0.png)

**Poly(A) site annotation:**
![image](https://user-images.githubusercontent.com/93919928/206456280-f3e7899b-59b9-4103-9133-dcdc2cfb1b21.png)
![image](https://user-images.githubusercontent.com/93919928/206456328-fb492f16-4ece-469c-8681-ff9ef8cf5829.png)
![image](https://user-images.githubusercontent.com/93919928/206456349-39cf3d6d-0929-4114-9a14-713a84d6609a.png)

**Output UTR from qapa build:**
![image](https://user-images.githubusercontent.com/93919928/206456419-ea62c6e8-bcb1-45db-a234-3d18596af197.png)
![image](https://user-images.githubusercontent.com/93919928/206456449-415a8d4f-559a-49a9-b936-f5961e4bcf81.png)
(In fourth column of output_utr.bed Ensemble Gene name is given as gene name, could this carry any issues?)

**Output sequences from qapa fasta:**
![image](https://user-images.githubusercontent.com/93919928/206456839-51427d96-d90a-4439-8792-05c83a70964f.png)

**UTR library from salmon index:**
![image](https://user-images.githubusercontent.com/93919928/206456914-8d416d78-7022-4918-ab48-340aacd71c72.png)
![image](https://user-images.githubusercontent.com/93919928/206456977-409f9017-6acd-4740-802a-bef70b742efe.png)

**ERROR qapa quant:**
![image](https://user-images.githubusercontent.com/93919928/206457091-d6ff24b0-ae2f-4e97-ac8c-30b2662bc78c.png)

Thank you very much for your effort!
Jaki

**Comment by kcha** [comment]
@jakiwaibl yes I think the issue is that there is a mismatch between identifier formats. The database file expects Ensembl Gene ID while your custom file is using gene symbols.
