### ISSUE TITLE
error about qapa build

### ISSUE THREAD

**Issue by lucifer9288** [morrislab/qapa#50]
hello, i want to apply the software in species not human and mouse, but i meet some problems at the process of build 3′ UTRs from annotation. I am very grateful that you can give me some help! the code and error is in the below:

qapa build -N --db bos_ensembl_identifiers.txt bos_custom_genes_ensem109.genePred > bos_output.utrs.bedqapa.qapa     - 2023-04-12 23:38:17,159 - INFO     - Version 1.3.3
qapa.qapa     - 2023-04-12 23:38:17,507 - INFO     - Extracting 3' UTRs from bos_custom_genes_ensem109.genePred
qapa.qapa     - 2023-04-12 23:38:20,148 - INFO     - Annotating 3' UTRs
qapa.annotate - 2023-04-12 23:38:20,994 - INFO     - Skipping annotation step
qapa.qapa     - 2023-04-12 23:38:22,170 - INFO     - Checking 5' ends
qapa.qapa     - 2023-04-12 23:38:48,178 - INFO     - Collapsing 3' ends
qapa.collapse - 2023-04-12 23:38:48,218 - INFO     - Sorting data frame by 3' end
qapa.collapse - 2023-04-12 23:38:48,225 - INFO     - Iterating and merging intervals by 3' end
qapa.collapse - 2023-04-12 23:38:49,017 - INFO     - Updating 5' end for each gene
qapa.qapa     - 2023-04-12 23:38:49,026 - ERROR    - Error occurred in build:
Traceback (most recent call last):
  File "/home/jh/mambaforge-pypy3/envs/qapa/lib/python3.10/site-packages/qapa/qapa.py", line 244, in build
    result = collapse.merge_bed(args, tf3.name)
  File "/home/jh/mambaforge-pypy3/envs/qapa/lib/python3.10/site-packages/qapa/collapse.py", line 147, in merge_bed
    forward = forward.drop('start_r', 1)
TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given

**Comment by hlldhy** [comment]
> 

I also encounter the same error,how to solve it?

**Comment by IanLopesTeixeira** [comment]
I also found it.

**Comment by YaJiang233** [comment]
I also found this problem. I think this is because of the updates of panda package. To change the code in "collapse.py", line 147 to `forward = forward.drop('start_r', axis=1)` may fix it. But I don't know how to contact the developer.

**Comment by olivertam** [comment]
Changing these two lines:
https://github.com/morrislab/qapa/blob/b7dd879edd063a114d9c5df9835d35c991390248/qapa/collapse.py#L147
https://github.com/morrislab/qapa/blob/b7dd879edd063a114d9c5df9835d35c991390248/qapa/collapse.py#L153
as described by @YaJiang233 (replacing `1` with `axis=1` worked for me.

**Comment by kcha** [comment]
@olivertam @YaJiang233 thank you for catching this!
