### ISSUE TITLE
Can qapa use for quantifying the other type apa, like intronic apa?

### ISSUE THREAD

**Issue by StaggererAyao** [morrislab/qapa#53]
Dear authors,

I got a custom BED file of poly(A) sites, which not only contain the 3utr zone, but also the other type zone, such as intronic exoinc. I wonder if we can flip the script to quantify the other type apa. If you can give directions to me, I would be more than grateful!

**Comment by kcha** [comment]
Sorry, QAPA wasn't designed to detect intronic APA.
