### ISSUE TITLE
Error:Failed to find any overlap between UTRs and annotation

### ISSUE THREAD

**Issue by pdxxxlm** [morrislab/qapa#55]
hey,
I am doing an APA analysis of rice using the build command.
ensembl_identifiers.txt has been downloaded and built from the Ensembl database.
custom sites.bed from a manual definition
And custom genes.genePred is built using GTF files.

There was such an error:
Failed to find any overlap between UTRs and annotation

<img width="725" alt="question" src="https://github.com/morrislab/qapa/assets/84006649/4a480b4e-0f91-43ea-8ca0-8817a7215ab2">

**Comment by kcha** [comment]
This usually means it was unable to map your Ensembl gene identifiers with your custom annotations. Maybe check if the format of your coordinates like chromosome are correctly formatted in both places.
