### ISSUE TITLE
Extract 3'UTR issue

### ISSUE THREAD

**Issue by fhh819** [morrislab/qapa#8]
I am pleased to perform QAPA, however, i had problem as i had used the program. Can you give me some suggestions? Thanks! Attachment is screenshot of error.
![qapa](https://user-images.githubusercontent.com/42135582/43705144-556c251a-9994-11e8-9e98-2470d23d5ddb.png)

**Comment by kcha** [comment]
Hi @fhh819 , thanks for sending me your files over e-mail. It appears that the format of your `custom_sites_1.bed` file is incorrect. It needs to be in a proper BED file format. Can you correct it and try again?

**Comment by fhh819** [comment]
Hi @kcha ,Thanks,can you send the format of correct to me, or send extracted 3'UTR.bed of  C. elegans to me? many thanks!

**Comment by kcha** [comment]
You can find a description of BED format here: https://useast.ensembl.org/info/website/upload/bed.html

**Comment by fhh819** [comment]
Hi @kcha ,The first three fields of BED file are required and my BED file format is proper,but it do not work using QAPA

**Comment by fhh819** [comment]
OK,I will try,thanks!
